Style Guide
exasol/lua-styleguide pull request #2
Opened 2022-05-25 13:50 UTC by redcatbear

Closes #1.

2022-05-25 14:18 UTC, Nicoretti approved these changes

2022-05-25 14:18 UTC, Nicoretti commented on doc/lua_style_guide.md
> +### Excursion: Extending Existing Lua Modules
In case you didn't know yet, this is also called [monkey patching](https://en.wikipedia.org/wiki/Monkey_patch) ;)

very rarely a good idea ;)

2022-05-25 14:18 UTC, Nicoretti commented on doc/lua_style_guide.md
> +We recommend the [`busted`](https://olivinelabs.com/busted/) framework for unit testing:
recommend? shouldn't it be unified?

2022-05-25 15:17 UTC, kaklakariada requested changes

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +A line of code has a maximum of 120 characters. Use concatenation where lines overflow. While Lua has no specific hard limit at 120 characters, it nevertheless is a decent compromise between having e
```suggestion
A line of code has a maximum of 120 characters. Use concatenation where lines overflow. While Lua has no specific hard limit at 120 characters, it nevertheless is a decent compromise between having enough space to avoid forced line breaks most of the time and getting a complete line displayed in most tools and on most displays.

You can check the line width in CI by calling `luacheck` with argument `--max-line-length 120`.
```

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +return connection_definition
```suggestion
return ConnectionDefinition
```
❓

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +
Add a note for file naming of modules in lower snake case.

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +}
👍  again what learned ;)

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +Don't mix the `_` variable up with variable names starting with a single underscore. Those traditionally indicate [private methods](#private-and-protected-methods) .
```suggestion
Don't mix the `_` variable up with variable names starting with a single underscore. Those traditionally indicate [private methods](#private-and-protected-methods).
```

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +Keep internal module and class consistent with the files they reside in. While it is any often seen standard to simply name modules `M` inside a module file, we recommend writing out the full name. F
```suggestion
Keep internal module and class consistent with the files they reside in. While it is an often seen standard to simply name modules `M` inside a module file, we recommend writing out the full name. First, that is more self-documenting, second it fits better when defining classes as modules.
```

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +And typing effort is not a valid argument given the auto-completion features of any modern IDE. Even domain abbreviations can be a problem if a reviewer or new code maintainer does not know that doma
```suggestion
And typing effort is not a valid argument given the auto-completion features of any modern IDE. Even domain abbreviations can be a problem if a reviewer or new code maintainer does not know that domain too well.
```

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +Put binary operators in front of the continued line in order to make the continuation more obvious.
```suggestion
Put binary operators in front of the continued line in order to make the continuation more obvious.

You can automatically enforce this rule with `lua-format` by adding the following to its config file `.lua-format`:

```lua
column_limit: 120
indent_width: 4
use_tab: false
continuation_indent_width: 8
```
```

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +Put binary operators in front of the continued line in order to make the continuation more obvious.
We could add a recommended configuration for lua-format, e.g. https://github.com/exasol/exasol-driver-lua/blob/main/.lua-format

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +While you theoretically can contract trivial blocks into a single line, it is often harder to read them this way. Avoid this kind of contraction unless you really need to conserve vertical space.
```suggestion
While you theoretically can contract trivial blocks into a single line, it is often harder to read them this way. Avoid this kind of contraction unless you really need to conserve vertical space.

Add a trailing comment `--` to force lua-format to preserve a line break.
```

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +Note that indentation rules take precedence over the rules above.
```suggestion
Note that indentation rules take precedence over the rules above.

You can automatically enforce this rule with `lua-format` by adding the following to its config file `.lua-format`:
```lua
spaces_before_call: 1
spaces_inside_functioncall_parens: false
spaces_inside_functiondef_parens: false
spaces_inside_table_braces: false
spaces_around_equals_in_field: true
```
```

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +All comments are written in English. This is the [lingua franca](https://en.wikipedia.org/wiki/Lingua_franca) (pun intended) of all professional programmers around the world. Since we want the code t
:-D

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +| Performance critical algorithm                              | This is a case where an explanation in form of a comment is acceptable |
```suggestion
| Performance critical algorithm                              | In this is a case an explanation in form of a comment is acceptable    |
```

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +assert.True(true)
```suggestion
assert.true(true)
```
❓

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +In the end users have to install those scripts in the database via an SQL client as inline text.
```suggestion
In the end, users have to install those scripts in the database via an SQL client as inline text.
```
At first i read "end users"

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +Also in case of scripts or adapter scripts, you should create bundles that contain all dependencies. We recommend using [`lua-amalg`](https://github.com/siffiejoe/lua-amalg/) for this particular purp
```suggestion
Also in case of scripts or adapter scripts, you should create bundles that contain all dependencies. We recommend using [`lua-amalg`](https://github.com/siffiejoe/lua-amalg/) for this particular purpose. Note that you cannot use debug-enabled amalg bundles (command line option `-d` or `--debug`) with Exasol, since the debug library was intentionally removed for security purposes.
```

2022-05-25 15:17 UTC, kaklakariada commented on doc/lua_style_guide.md
> +If you have a simple build, we recommend using [LuaRock's built-in support for building rocks](https://github.com/luarocks/luarocks/wiki/Creating-a-rock#building-a-module). It can build both pure-Lua
```suggestion
If you have a simple build, we recommend using [LuaRock's built-in support for building rocks](https://github.com/luarocks/luarocks/wiki/Creating-a-rock#building-a-module). It can build both pure-Lua and Lua / C mixed packages. In the context of Exasol scripts only pure-lua packages are relevant, since loading binary code is explicitly disabled.
```

2022-05-27 04:48 UTC, redcatbear commented on doc/lua_style_guide.md
> +assert.True(true)
`true` is a reserved word.

2022-05-27 05:19 UTC, kaklakariada commented on doc/lua_style_guide.md
> +assert.True(true)
👍

2022-05-27 05:20 UTC, kaklakariada approved these changes

2022-05-27 05:22 UTC, merged